-- Generated by nwg-displays on 2026-09-03 at 18:37:15. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.03",
    position = "0x0",
    scale = 0.9999999999999997
})
