# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E3EAE8
background         #000008
cursor             #A3ABA7

active_tab_foreground     #000008
active_tab_background     #E3EAE8
inactive_tab_foreground   #E3EAE8
inactive_tab_background   #000008

active_border_color   #E3EAE8
inactive_border_color #000008
bell_border_color     #212D3E

color0      #000008
color1		#212D3E
color2		#4A504C
color3		#48565E
color4		#706235
color5		#6F7E7E
color6		#82928E
color7		#CED9D6
color8		#909895
color9		#2D3C52
color10		#636B66
color11		#60727D
color12		#968247
color13		#94A8A8
color14		#AEC3BD
color15		#CED9D6
