# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000008)
$foreground = rgb(E3EAE8)
$color0 = rgb(000008)
$color1 = rgb(212D3E)
$color2 = rgb(4A504C)
$color3 = rgb(48565E)
$color4 = rgb(706235)
$color5 = rgb(6F7E7E)
$color6 = rgb(82928E)
$color7 = rgb(CED9D6)
$color8 = rgb(909895)
$color9 = rgb(2D3C52)
$color10 = rgb(636B66)
$color11 = rgb(60727D)
$color12 = rgb(968247)
$color13 = rgb(94A8A8)
$color14 = rgb(AEC3BD)
$color15 = rgb(CED9D6)
